import { useState, useEffect, useRef } from 'react';
import './App.css';

const API_BASE_URL = "https://hasanmujtaba-scan2ebook-ai.hf.space";

function App() {
  // Theme State (Default to dark if user prefers it)
  const [theme, setTheme] = useState('light');
  
  const [file, setFile] = useState(null);
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);
  
  // Book Metadata
  const [pages, setPages] = useState([]);
  const [bookTitle, setBookTitle] = useState("");
  const [authorName, setAuthorName] = useState("");

  const cameraInputRef = useRef(null);
  const galleryInputRef = useRef(null);

  // Toggle Theme Function
  const toggleTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light';
    setTheme(newTheme);
  };

  // Apply theme to body
  useEffect(() => {
    document.body.setAttribute('data-theme', theme);
  }, [theme]);

  const handleFileSelect = (e) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  const handleProcess = async () => {
    if (!file) return alert("Please select a file first!");
    setLoading(true);
    
    const formData = new FormData();
    formData.append("file", file);

    try {
      const response = await fetch(`${API_BASE_URL}/process-page`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        const err = await response.json();
        throw new Error(err.detail || "Backend Error");
      }

      const data = await response.json();
      setContent(data.clean);
    } catch (error) {
      console.error(error);
      alert("Error: " + error.message);
    } finally {
      setLoading(false);
    }
  };

  const addPage = () => {
    if (!content) return;
    setPages([...pages, content]);
    setContent(""); 
    setFile(null);
    alert(`Page ${pages.length + 1} Added!`);
  };

  const downloadBook = () => {
    if (pages.length === 0) return alert("No pages to save!");
    const title = bookTitle || "My Urdu Book";
    const author = authorName || "Unknown Author";

    const htmlHead = `
      <html>
        <head>
          <meta charset="utf-8">
          <title>${title}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; direction: rtl; text-align: right; background: #f9f9f9; }
            .cover { text-align: center; padding: 100px 20px; background: white; border: 5px double #4f46e5; margin-bottom: 50px; page-break-after: always; }
            .index { background: white; padding: 40px; margin-bottom: 50px; border: 1px solid #ddd; page-break-after: always; }
            .page { background: white; padding: 40px; margin-bottom: 30px; border: 1px solid #ddd; border-radius: 8px; page-break-after: always; }
            h1 { color: #4f46e5; }
            p { font-size: 1.3rem; line-height: 2; }
          </style>
        </head>
        <body>
    `;

    const coverHTML = `
      <div class="cover">
        <h1 style="font-size:3rem;">${title}</h1>
        <p style="font-size:1.5rem; color:#555;">Written by: ${author}</p>
        <p style="margin-top:50px; color:#888;">Generated by Scan2Ebook AI</p>
      </div>`;

    let indexHTML = `<div class="index"><h1>فہرست (Index)</h1>`;
    pages.forEach((_, i) => indexHTML += `<div style="display:flex; justify-content:space-between; border-bottom:1px dotted #ccc; padding:10px 0;"><span>Page ${i+1}</span><span>صفحہ ${i+1}</span></div>`);
    indexHTML += `</div>`;

    const pagesHTML = pages.map((text, i) => `<div class="page"><h2>Page ${i+1}</h2><p>${text}</p></div>`).join("");
    
    const blob = new Blob([htmlHead + coverHTML + indexHTML + pagesHTML + "</body></html>"], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_')}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="App">
      {/* Header with Theme Toggle */}
      <header className="header">
        <h1>📱 Scan2Ebook AI</h1>
        <button className="theme-toggle" onClick={toggleTheme} title="Switch Theme">
          {theme === 'light' ? '🌙' : '☀️'}
        </button>
      </header>
      
      {/* Inputs */}
      <div className="meta-inputs">
        <input className="text-input" type="text" value={bookTitle} onChange={(e) => setBookTitle(e.target.value)} placeholder="📖 Book Title" />
        <input className="text-input" type="text" value={authorName} onChange={(e) => setAuthorName(e.target.value)} placeholder="✍️ Author Name" />
      </div>

      <div className="upload-container">
        <input type="file" accept="image/*" capture="environment" ref={cameraInputRef} style={{ display: 'none' }} onChange={handleFileSelect} />
        <input type="file" accept="image/*" ref={galleryInputRef} style={{ display: 'none' }} onChange={handleFileSelect} />

        <div className="button-group">
          <button className="action-btn camera-btn" onClick={() => cameraInputRef.current.click()}>📸 Camera</button>
          <button className="action-btn gallery-btn" onClick={() => galleryInputRef.current.click()}>🖼️ Gallery</button>
        </div>
        <p style={{marginTop: '10px', fontSize: '0.9rem', color: 'var(--text-secondary)'}}>
          {file ? `✅ ${file.name}` : "Select a page to scan"}
        </p>
      </div>

      <button className="primary-btn" onClick={handleProcess} disabled={loading}>
        {loading ? "Scanning & Cleaning..." : "✨ Start Magic Scan"}
      </button>

      <textarea 
        className="editor-box"
        value={content} 
        onChange={(e) => setContent(e.target.value)}
        dir="rtl" 
        placeholder="Scanned Urdu text will appear here for editing..."
      />

      <div className="book-actions">
        <button className="secondary-btn" onClick={addPage} disabled={!content}>
          ➕ Add Page ({pages.length})
        </button>
        
        {pages.length > 0 && (
          <button className="download-btn" onClick={downloadBook}>
            📥 Download eBook
          </button>
        )}
      </div>

      {/* Signature Footer */}
      <footer className="footer">
        <p>Made with <span className="heart">❤️</span> by <strong>Hasan</strong></p>
        <p style={{fontSize: '0.8rem', opacity: 0.7}}>Powered by Llama 3.1 & PaddleOCR</p>
      </footer>
    </div>
  );
}

export default App;