import { useState, useRef } from 'react';
import './App.css';

// Your backend URL
const API_BASE_URL = "https://hasanmujtaba-scan2ebook-ai.hf.space";

function App() {
  const [file, setFile] = useState(null);
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);
  
  // Book Metadata
  const [pages, setPages] = useState([]);
  const [bookTitle, setBookTitle] = useState("");
  const [authorName, setAuthorName] = useState("");

  const cameraInputRef = useRef(null);
  const galleryInputRef = useRef(null);

  const handleFileSelect = (e) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
    }
  };

  const handleProcess = async () => {
    if (!file) return alert("Please select a file first!");
    setLoading(true);
    
    const formData = new FormData();
    formData.append("file", file);

    try {
      const response = await fetch(`${API_BASE_URL}/process-page`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        const err = await response.json();
        throw new Error(err.detail || "Backend Error");
      }

      const data = await response.json();
      setContent(data.clean);
    } catch (error) {
      console.error(error);
      alert("OCR Failed: " + error.message);
    } finally {
      setLoading(false);
    }
  };

  const addPage = () => {
    if (!content) return;
    setPages([...pages, content]);
    setContent(""); 
    setFile(null);
    alert(`Page ${pages.length + 1} Added!`);
  };

  // ✅ NEW: Advanced Book Generator (Cover + Index + Pages)
  const downloadBook = () => {
    if (pages.length === 0) return alert("No pages to save!");
    const title = bookTitle || "My Urdu Book";
    const author = authorName || "Unknown Author";

    // 1. HTML Header & Style
    const htmlHead = `
      <html>
        <head>
          <meta charset="utf-8">
          <title>${title}</title>
          <style>
            body { 
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
              padding: 40px; 
              max-width: 800px; 
              margin: 0 auto; 
              direction: rtl; 
              text-align: right;
              background-color: #f9f9f9;
            }
            .cover-page {
              text-align: center;
              padding: 100px 20px;
              background: white;
              border: 5px double #4f46e5;
              margin-bottom: 50px;
              page-break-after: always; /* Force new page after cover */
            }
            .cover-title { font-size: 3rem; color: #4f46e5; margin-bottom: 20px; }
            .cover-author { font-size: 1.5rem; color: #555; }
            
            .index-page {
              background: white;
              padding: 40px;
              margin-bottom: 50px;
              border: 1px solid #ddd;
              page-break-after: always;
            }
            .index-item {
              display: flex;
              justify-content: space-between;
              border-bottom: 1px dotted #ccc;
              padding: 10px 0;
              font-size: 1.2rem;
            }

            .content-page { 
              background: white; 
              padding: 40px; 
              margin-bottom: 30px; 
              border: 1px solid #ddd; 
              border-radius: 8px;
              page-break-after: always;
            }
            h2 { color: #666; border-bottom: 1px solid #eee; padding-bottom: 10px; }
            p { font-size: 1.3rem; line-height: 2; white-space: pre-wrap; }
          </style>
        </head>
        <body>
    `;

    // 2. Build Cover Page
    const coverPageHTML = `
      <div class="cover-page">
        <h1 class="cover-title">${title}</h1>
        <p class="cover-author">Written by: ${author}</p>
        <p style="margin-top:50px; color:#888;">Generated by Scan2Ebook AI</p>
      </div>
    `;

    // 3. Build Index Page (Table of Contents)
    let indexHTML = `<div class="index-page"><h1>فہرست (Index)</h1>`;
    pages.forEach((_, i) => {
      indexHTML += `
        <div class="index-item">
          <span>Page ${i + 1}</span>
          <span>................................</span>
          <span>صفحہ ${i + 1}</span>
        </div>`;
    });
    indexHTML += `</div>`;

    // 4. Build Content Pages
    const pagesHTML = pages.map((pageText, index) => `
      <div class="content-page">
        <h2>Page ${index + 1}</h2>
        <p>${pageText}</p>
      </div>
    `).join("");

    const fullContent = htmlHead + coverPageHTML + indexHTML + pagesHTML + "</body></html>";

    // 5. Download
    const blob = new Blob([fullContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_')}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="App">
      <h1>📱 Scan2Ebook AI</h1>
      
      {/* Metadata Inputs */}
      <div className="meta-inputs">
        <input 
          className="text-input"
          type="text" 
          value={bookTitle} 
          onChange={(e) => setBookTitle(e.target.value)}
          placeholder="Book Title (किताब का नाम)"
        />
        <input 
          className="text-input"
          type="text" 
          value={authorName} 
          onChange={(e) => setAuthorName(e.target.value)}
          placeholder="Author Name (लेखक)"
        />
      </div>

      <div className="upload-container">
        {/* Hidden Inputs */}
        <input type="file" accept="image/*" capture="environment" ref={cameraInputRef} style={{ display: 'none' }} onChange={handleFileSelect} />
        <input type="file" accept="image/*" ref={galleryInputRef} style={{ display: 'none' }} onChange={handleFileSelect} />

        <div className="button-group">
          <button className="action-btn camera-btn" onClick={() => cameraInputRef.current.click()}>📸 Photo</button>
          <button className="action-btn gallery-btn" onClick={() => galleryInputRef.current.click()}>🖼️ Gallery</button>
        </div>
        <p style={{marginTop: '10px', fontWeight: 'bold'}}>{file ? `✅ ${file.name}` : "Select a page"}</p>
      </div>

      <button className="primary-btn" onClick={handleProcess} disabled={loading}>
        {loading ? "Scanning..." : "✨ Scan Page"}
      </button>

      <textarea 
        className="editor-box"
        value={content} 
        onChange={(e) => setContent(e.target.value)}
        dir="rtl" 
        placeholder="Scanned text will appear here..."
      />

      <div className="book-actions">
        <button className="secondary-btn" onClick={addPage} disabled={!content}>
          ➕ Add Page ({pages.length})
        </button>
        
        {pages.length > 0 && (
          <button className="download-btn" onClick={downloadBook}>
            📚 Download Full Book
          </button>
        )}
      </div>
    </div>
  );
}

export default App;